import Navbar from "@/components/Navbar";
import AuthProvider from "@/providers/AuthProvider";

import "./globals.scss";

export const metadata = {
  title: "Adoption",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`app`}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
