import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import AuthProvider from "@/providers/AuthProvider";

import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`app ${inter.className}`}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
